apiVersion: apps/v1
kind: Deployment                                # Creates a Deployment named spring-boot-k8s-yaml
metadata:
  name: spring-boot-k8s-yaml
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s-yaml
  replicas: 2                                     # Runs 2 replicas (Pods) of your Spring Boot container
  template:
    metadata:
      labels:
        app: spring-boot-k8s-yaml
    spec:
      containers:
        - name: spring-boot-k8s-yaml
          image: spring-boot-k8s-app-yaml:1.0     # Image that will be used to containers in the cluster [docker build -t spring-boot-k8s-app-yaml:1.0 .]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080                 # The port that the container is running on in the cluster

# kubectl apply -f deployment.yaml
# kubectl get pods
